# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\formulario1.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pandas as pd


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(930, 634)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 10, 91, 41))
        self.label.setObjectName("label")
        self.le_nombre = QtWidgets.QLineEdit(self.centralwidget)
        self.le_nombre.setGeometry(QtCore.QRect(420, 10, 141, 31))
        self.le_nombre.setObjectName("le_nombre")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(300, 70, 91, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(300, 140, 91, 31))
        self.label_3.setObjectName("label_3")
        self.cb_tetra = QtWidgets.QComboBox(self.centralwidget)
        self.cb_tetra.setGeometry(QtCore.QRect(420, 80, 121, 21))
        self.cb_tetra.setObjectName("cb_tetra")
        self.cb_tetra.addItem("")
        self.cb_tetra.addItem("")
        self.cb_tetra.addItem("")
        self.cb_carrera = QtWidgets.QComboBox(self.centralwidget)
        self.cb_carrera.setGeometry(QtCore.QRect(420, 140, 141, 21))
        self.cb_carrera.setObjectName("cb_carrera")
        self.cb_carrera.addItem("")
        self.cb_carrera.addItem("")
        self.cb_carrera.addItem("")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(290, 210, 101, 31))
        self.label_4.setObjectName("label_4")
        self.le_matricula = QtWidgets.QLineEdit(self.centralwidget)
        self.le_matricula.setGeometry(QtCore.QRect(420, 200, 141, 31))
        self.le_matricula.setObjectName("le_matricula")
        self.pb_guardar = QtWidgets.QPushButton(self.centralwidget)
        self.pb_guardar.setGeometry(QtCore.QRect(430, 270, 93, 28))
        self.pb_guardar.setObjectName("pb_guardar")
        self.tabla = QtWidgets.QTableWidget(self.centralwidget)
        self.tabla.setGeometry(QtCore.QRect(240, 350, 441, 221))
        self.tabla.setObjectName("tabla")
        self.tabla.setColumnCount(0)
        self.tabla.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.pb_guardar.clicked.connect(self.guardar)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Nombre"))
        self.label_2.setText(_translate("MainWindow", "Tetra"))
        self.label_3.setText(_translate("MainWindow", "Carrera"))
        self.cb_tetra.setItemText(0, _translate("MainWindow", "1ro"))
        self.cb_tetra.setItemText(1, _translate("MainWindow", "2do"))
        self.cb_tetra.setItemText(2, _translate("MainWindow", "3ro"))
        self.cb_carrera.setItemText(0, _translate("MainWindow", "isc"))
        self.cb_carrera.setItemText(1, _translate("MainWindow", "im"))
        self.cb_carrera.setItemText(2, _translate("MainWindow", "ita"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.pb_guardar.setText(_translate("MainWindow", "Guardar"))

    def guardar(self):
        df = pd.read_csv('registros.csv')

        n = self.le_nombre.text()
        t = self.cb_tetra.currentText()
        c = self.cb_carrera.currentText()
        m = self.le_matricula.text()

        registro = [(n, t, c, m)]

        df1 = pd.DataFrame(registro, columns=['Nombre', 'Tetra', 'Carrera', 'Matricula'])

        df = df.append(df1, ignore_index=True)

        eliminar_colum = [col for col in df.columns if 'Unnamed' in col]
        df.drop(eliminar_colum, axis='columns', inplace=True)

        df.to_csv('registros.csv')

        self.tabla.setColumnCount(len(df.columns))
        self.tabla.setRowCount(len(df))
        self.tabla.setHorizontalHeaderLabels(df.columns)

        for i in range(len(df)):
            for j in range(len(df.columns)):
                self.tabla.setItem(i, j, QtWidgets.QTableWidgetItem(str(df.iat[i, j])))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
