# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prestamos_bancarios.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(978, 717)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-20, -40, 1021, 731))
        self.label.setStyleSheet("image: url(:/imagenes/fondo_proyecto.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(330, 70, 341, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.btn_solicitar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_solicitar.setGeometry(QtCore.QRect(400, 210, 141, 61))
        self.btn_solicitar.setObjectName("btn_solicitar")
        self.btn_planes = QtWidgets.QPushButton(self.centralwidget)
        self.btn_planes.setGeometry(QtCore.QRect(400, 370, 131, 61))
        self.btn_planes.setObjectName("btn_planes")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;"
                                                      " color:#ffffff;\">Prestamos Bancarios</span></p></body></html>"))
        self.btn_solicitar.setText(_translate("MainWindow", "Solicitar"))
        self.btn_planes.setText(_translate("MainWindow", "Planes"))
import imagenes_rc
